# Generated by Django 5.1.6 on 2025-03-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('storage', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('blood_type', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=255)),
                ('contacts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=150)),
                ('user_contact_information', models.TextField()),
                ('request_type', models.CharField(max_length=100)),
                ('request_location', models.CharField(max_length=255)),
                ('donor_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('donor_location', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_type', models.CharField(max_length=5)),
                ('unit', models.CharField(max_length=20)),
                ('status', models.BooleanField(choices=[(True, 'completed'), (False, 'pending')], default=False)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='MYUSER.userinfo')),
                ('user_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='MYUSER.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PastDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=255)),
                ('donation_for', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_donations', to='MYUSER.userinfo')),
            ],
        ),
    ]
