# Generated by Django 5.1.6 on 2025-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYUSER', '0002_sosnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankDetails',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('a_positive', models.IntegerField(default=0)),
                ('b_positive', models.IntegerField(default=0)),
                ('o_positive', models.IntegerField(default=0)),
                ('ab_positive', models.IntegerField(default=0)),
                ('a_negative', models.IntegerField(default=0)),
                ('b_negative', models.IntegerField(default=0)),
                ('o_negative', models.IntegerField(default=0)),
                ('ab_negative', models.IntegerField(default=0)),
            ],
        ),
    ]
